import {api,esc,money,photo,notify,toggleModal} from './common.js';
export function catalogView(db){const cats=[...db.categories].sort((a,b)=>Number(a.position||0)-Number(b.position||0));return `<div class="row between wrap" style="margin-bottom:18px"><div class="subnav"><button class="chip selected" data-nav="catalog">Organização geral</button><button class="chip" data-nav="products">Produtos</button><button class="chip" data-nav="addon_groups">Complementos</button></div><button class="primary" data-new="categories">+ Categoria</button></div><p class="small muted">Arraste pela alça ⠿ para reorganizar categorias e produtos. Clique em um grupo para expandir.</p><div id="catalog-tree">${cats.map(c=>`<section class="catalog-category card" draggable="true" data-drag-cat="${esc(c.id)}"><div class="catalog-heading"><span class="draghandle" title="Arrastar categoria">⠿</span><button class="catalog-collapse" data-expand="${esc(c.id)}">▾</button><div class="grow"><b>${esc(c.name)}</b><div class="small muted">${esc(c.description||'')} · ${db.products.filter(p=>p.category_id===c.id).length} produtos</div></div><span class="status ${c.active?'':'off'}">${c.active?'Ativa':'Pausada'}</span><button class="iconbtn" data-edit="categories:${esc(c.id)}">✎</button><button class="iconbtn" data-toggle="categories:${esc(c.id)}">${c.active?'⏸':'▶'}</button><button class="secondary" data-cat-groups="${esc(c.id)}">+ Complementos da categoria</button><button class="secondary" data-add-product="${esc(c.id)}">+ Produto</button></div><div class="catalog-items" data-zone="${esc(c.id)}">${db.products.filter(p=>p.category_id===c.id).sort((a,b)=>Number(a.position||0)-Number(b.position||0)).map(p=>`<div class="catalog-product" draggable="true" data-drag-product="${esc(p.id)}"> <span class="draghandle">⠿</span>${photo(p,'catalogthumb')}<div class="grow"><b>${esc(p.name)}</b><div class="small muted">${money(p.sale_price||p.price)} · ${(p.group_ids||'').split(',').filter(Boolean).length} grupos de escolha</div></div><button class="iconbtn" title="Configurar produto" data-edit="products:${esc(p.id)}">✎</button><button class="iconbtn" title="Adicionar grupo" data-link-group="${esc(p.id)}">⊕</button><button class="iconbtn" title="Pausar/ativar" data-toggle="products:${esc(p.id)}">${p.active?'⏸':'▶'}</button></div>`).join('')}<button class="catalog-add" data-add-product="${esc(c.id)}">+ Adicionar produto nesta categoria</button></div></section>`).join('')}</div>`}
export function groupTable(db){return `<div class="row between wrap" style="margin-bottom:15px"><p class="muted">Perguntas reutilizáveis com opções, preços e seleção obrigatória ou opcional.</p><button class="primary" data-create-group>+ Novo grupo</button></div><div class="grid" style="gap:12px">${db.addon_groups.map(g=>{let opts=[];try{opts=JSON.parse(g.options||'[]')}catch{}return `<div class="card panel"><div class="row between wrap"><div><b>${esc(g.name)}</b><div class="small muted">${opts.length} opções · ${g.required?'Obrigatório':'Opcional'} · até ${g.max_select||opts.length} unidades</div></div><div class="row"><span class="status ${g.active?'':'off'}">${g.active?'Ativo':'Pausado'}</span><button class="iconbtn" data-edit-group="${esc(g.id)}">✎</button><button class="iconbtn" data-toggle="addon_groups:${esc(g.id)}">${g.active?'⏸':'▶'}</button><button class="iconbtn" data-delete="addon_groups:${esc(g.id)}">✕</button></div></div><div class="small muted" style="margin-top:8px">${opts.map(o=>`${esc(o.name)}${o.product_id?' ↗':''}${o.price!==''&&o.price!=null?' · '+money(o.price):''}${o.active===false?' (pausado)':''}`).join(' · ')}</div></div>`}).join('')}</div>`}
export function groupEditor(db,existing={},done=()=>{}){let options=[];try{options=JSON.parse(existing.options||'[]')}catch{};const m=toggleModal(`<div class="row between"><h2>${existing.id?'Editar':'Novo'} grupo de escolhas</h2><button class="iconbtn" data-close>✕</button></div><form id="group-form"><label class="field">Pergunta / título do grupo</label><input class="input" name="name" required placeholder="Ex.: Escolha os sabores" value="${esc(existing.name||'')}"><div class="formgrid"><div><label class="field">Mínimo de escolhas</label><input class="input" name="min_select" type="number" min="0" value="${existing.min_select??0}"></div><div><label class="field">Máximo de escolhas</label><input class="input" name="max_select" type="number" min="1" value="${existing.max_select??1}"></div></div><label class="field">Opções sem valor</label><select class="input" name="free_label"><option value="" ${!existing.free_label?'selected':''}>Não mostrar nada (padrão)</option><option value="gratis" ${existing.free_label==='gratis'?'selected':''}>Mostrar Grátis</option></select><label class="checkboxline"><input type="checkbox" name="required" ${existing.required?'checked':''}> Resposta obrigatória</label><label class="checkboxline"><input type="checkbox" name="active" ${existing.active===false?'':'checked'}> Grupo ativo</label><h3>Alternativas</h3><div id="group-options"></div><button type="button" class="secondary" id="add-option">+ Criar alternativa</button><button type="button" class="outline" id="pull-product">+ Usar produto cadastrado</button><div class="actions"><button type="button" class="outline" data-close>Cancelar</button><button class="primary">Salvar grupo</button></div></form>`);
function draw(){m.querySelector('#group-options').innerHTML=options.map((o,i)=>`<div class="option-editor" data-option="${i}"><div class="row between"><b class="small">Opção ${i+1}</b><button type="button" class="iconbtn" data-remove-option="${i}">✕</button></div><label class="field">Nome</label><input class="input" data-opt-name="${i}" value="${esc(o.name||'')}"><label class="field">Valor adicional (R$) ${o.product_id?'— vazio usa preço do produto':''}</label><input class="input" data-opt-price="${i}" type="number" min="0" step="0.01" value="${o.price??''}" placeholder="${o.product_id?'Usar preço do produto':'0,00'}"><label class="checkboxline"><input type="checkbox" data-opt-active="${i}" ${o.active===false?'':'checked'}> Disponível</label>${o.product_id?`<div class="small muted">Vinculado ao produto: ${esc(db.products.find(p=>p.id===o.product_id)?.name||o.product_id)}</div>`:''}</div>`).join('');m.querySelectorAll('[data-remove-option]').forEach(x=>x.onclick=()=>{sync();options.splice(Number(x.dataset.removeOption),1);draw()})}
function sync(){options=options.map((o,i)=>({...o,name:m.querySelector(`[data-opt-name="${i}"]`)?.value.trim()||'',price:m.querySelector(`[data-opt-price="${i}"]`)?.value??'',active:!!m.querySelector(`[data-opt-active="${i}"]`)?.checked}))}
m.querySelector('#add-option').onclick=()=>{sync();options.push({id:crypto.randomUUID(),name:'',price:0,active:true});draw()};m.querySelector('#pull-product').onclick=()=>{sync();const names=db.products.map(p=>`${p.id} — ${p.name}`).join('\n');const id=prompt('Digite o ID do produto para vincular:\n'+names);const p=db.products.find(p=>p.id===id?.trim());if(!p)return id&&notify('Produto não encontrado');options.push({id:crypto.randomUUID(),product_id:p.id,name:p.name,price:'',active:true});draw()};draw();m.querySelector('#group-form').onsubmit=async e=>{e.preventDefault();sync();let fd=e.target;const name=fd.elements.name.value.trim(),min_select=Number(fd.elements.min_select.value),max_select=Number(fd.elements.max_select.value);if(!options.length||options.some(o=>!o.name))return notify('Preencha as alternativas');if(max_select<1||min_select>max_select)return notify('Confira os limites de escolhas');const data={name,min_select,max_select,free_label:fd.elements.free_label.value,required:fd.elements.required.checked,active:fd.elements.active.checked,position:existing.position||db.addon_groups.length+1,options:JSON.stringify(options)};try{await api('/manage/addon_groups'+(existing.id?'/'+existing.id:''),{method:existing.id?'PATCH':'POST',body:JSON.stringify(data)});m.remove();done();notify('Grupo salvo')}catch(err){notify(err.message)}}}
export function linkGroup(db,product,done){const ids=String(product.group_ids||'').split(',').filter(Boolean);const m=toggleModal(`<div class="row between"><h2>Complementos · ${esc(product.name)}</h2><button class="iconbtn" data-close>✕</button></div><p class="small muted">Vincule grupos existentes. Mudanças feitas no grupo serão aplicadas a todos os produtos associados.</p>${db.addon_groups.map(g=>`<label class="checkboxline"><input type="checkbox" data-group="${esc(g.id)}" ${ids.includes(g.id)?'checked':''}> ${esc(g.name)} ${g.active?'':'(pausado)'}</label>`).join('')||'<p>Nenhum grupo cadastrado. Crie um grupo na aba Complementos.</p>'}<div class="actions"><button class="primary" id="save-links">Salvar vínculos</button></div>`);m.querySelector('#save-links').onclick=async()=>{const group_ids=[...m.querySelectorAll('[data-group]:checked')].map(x=>x.dataset.group).join(',');try{await api('/manage/products/'+product.id,{method:'PATCH',body:JSON.stringify({group_ids})});m.remove();done();notify('Grupos vinculados')}catch(e){notify(e.message)}}}
export function catalogDrag(done){let moving=null;document.querySelectorAll('[data-drag-cat], [data-drag-product]').forEach(el=>{el.addEventListener('dragstart',e=>{if(e.target!==el)return;moving={type:el.dataset.dragCat?'cat':'product',id:el.dataset.dragCat||el.dataset.dragProduct};el.classList.add('dragging');e.dataTransfer.effectAllowed='move'});el.addEventListener('dragend',()=>{el.classList.remove('dragging');moving=null})});document.querySelectorAll('[data-drag-cat], [data-zone], [data-drag-product]').forEach(el=>{el.addEventListener('dragover',e=>{if(moving){e.preventDefault();e.dataTransfer.dropEffect='move'}});el.addEventListener('drop',async e=>{e.preventDefault();e.stopPropagation();if(!moving)return;let changes=[];if(moving.type==='cat'){const target=e.target.closest('[data-drag-cat]');const source=document.querySelector(`[data-drag-cat="${moving.id}"]`);if(!target||!source||target===source)return;target.parentNode.insertBefore(source,target);changes=[...document.querySelectorAll('[data-drag-cat]')].map((c,i)=>({table:'categories',id:c.dataset.dragCat,data:{position:i+1}}))}else{const zone=e.target.closest('[data-zone]')||e.target.closest('[data-drag-product]')?.parentElement;const source=document.querySelector(`[data-drag-product="${moving.id}"]`);if(!zone||!source)return;let target=e.target.closest('[data-drag-product]');if(target&&target!==source)zone.insertBefore(source,target);else zone.append(source);changes=[...zone.querySelectorAll('[data-drag-product]')].map((x,i)=>({table:'products',id:x.dataset.dragProduct,data:{position:i+1,category_id:zone.dataset.zone}}))}try{await api('/reorder',{method:'POST',body:JSON.stringify({changes})});done();notify('Ordem atualizada')}catch(e){notify(e.message);done()}})})}


export function categoryGroups(db, category, done) {
  const ids = String(category.group_ids || '').split(',').filter(Boolean);
  const modal = toggleModal(`<h2>Complementos de ${esc(category.name)}</h2><p class="small muted">Aplicados automaticamente a todos os produtos desta categoria.</p>
    ${db.addon_groups.map(g => `<label class="checkboxline"><input type="checkbox" data-cat-group="${esc(g.id)}" ${ids.includes(g.id) ? 'checked' : ''}> ${esc(g.name)}</label>`).join('')}
    <div class="actions"><button class="outline" data-close>Cancelar</button><button class="primary" id="save-category-groups">Salvar</button></div>`);
  modal.querySelector('#save-category-groups').onclick = async () => {
    const group_ids = [...modal.querySelectorAll('[data-cat-group]:checked')].map(x => x.dataset.catGroup).join(',');
    try {
      await api('/manage/categories/' + category.id, {method:'PATCH',body:JSON.stringify({group_ids})});
      modal.remove(); done(); notify('Complementos da categoria salvos');
    } catch(error) { notify(error.message); }
  };
}
