// @ts-nocheck
// MenuFlow API: Supabase Edge Function (Deno), sem PHP nem integrações Google.
import {createClient} from 'npm:@supabase/supabase-js@2';
const supabase=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});

const TABLES=['categories','products','addons','addon_groups','orders','banners','coupons','settings','loyalty','rewards'];
const DEFAULTS={store_name:'Minha loja',delivery_fee:'0',free_shipping:'75',open:'true',notice:'Bem-vindo!',primary:'#961406',secondary:'#d5411a',pix_key:''};
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'authorization, apikey, content-type','access-control-allow-methods':'POST, OPTIONS','content-type':'application/json; charset=utf-8'};
function assert(cond,message){if(!cond)throw Error(message)}
function errDB(error){if(error)throw Error('Erro do Supabase: '+error.message)}
function scrub(record){let obj={...record};for(const k of ['active','required','stock_enabled','exclude_sale'])if(k in obj)obj[k]=obj[k]===true||String(obj[k]).toLowerCase()==='true';return obj}
async function rows(table){assert(TABLES.includes(table),'Tabela inválida');let all=[],start=0;while(true){const {data,error}=await supabase.from('mf_records').select('data').eq('table_name',table).order('created_at',{ascending:true}).range(start,start+999);errDB(error);let part=data||[];all.push(...part.map(row=>scrub(row.data)));if(part.length<1000)break;start+=1000}return all}
async function save(table,id,data,mode){assert(TABLES.includes(table),'Tabela inválida');assert(table!=='settings','Configuração inválida');let item=null;if(mode==='PATCH'||mode==='DELETE'){const {data:old,error}=await supabase.from('mf_records').select('data').eq('table_name',table).eq('id',String(id)).maybeSingle();errDB(error);assert(old,'Registro não encontrado');item=old.data}
if(mode==='DELETE'){let {error}=await supabase.from('mf_records').delete().eq('table_name',table).eq('id',String(id));errDB(error);return {ok:true}}
let key=mode==='PATCH'?String(id):String(id||crypto.randomUUID().slice(0,12));item={...(item||{}),...(data||{}),id:key};let {error}=await supabase.from('mf_records').upsert({table_name:table,id:key,data:item},{onConflict:'table_name,id'});errDB(error);return item}
async function settings(){let s={...DEFAULTS};for(let item of await rows('settings'))s[item.key]=String(item.value??'');return s}
async function updateSettings(data){for(let [key,value] of Object.entries(data||{})){if(!(key in DEFAULTS))continue;let {error}=await supabase.from('mf_records').upsert({table_name:'settings',id:key,data:{key,value:String(value)}},{onConflict:'table_name,id'});errDB(error)}return settings()}
async function publicData(){let out={};for(let t of ['categories','products','addons','addon_groups','banners','rewards'])out[t]=(await rows(t)).filter(x=>x.active);return {...out,coupons:[],orders:[],settings:await settings()}}
async function authorized(token){
 assert(typeof token==='string'&&token.length>30,'Faça login para acessar o painel');
 const {data:{user},error}=await supabase.auth.getUser(token);
 assert(!error&&user?.id,'Sessão inválida ou expirada');
 const {data:allowed,error:dbError}=await supabase.from('mf_admins').select('user_id').eq('user_id',user.id).maybeSingle();
 errDB(dbError);assert(!!allowed,'Usuário sem permissão administrativa');
}
async function commitCheckout(order,used){let {data,error}=await supabase.rpc('mf_commit_checkout',{p_order:order,p_stock:used});errDB(error);return data}
async function upload(p){assert(/^image\/(jpeg|png|webp|gif)$/.test(String(p.mime||'')),'Formato de imagem inválido');assert(typeof p.base64==='string'&&p.base64.length<6000000,'Imagem acima do limite');const buf=Uint8Array.from(atob(p.base64),c=>c.charCodeAt(0));assert(buf.length<=4*1024*1024,'Imagem acima de 4 MB');let ext=p.mime.split('/')[1],path=crypto.randomUUID()+'.'+ext;let {error}=await supabase.storage.from('menu-images').upload(path,buf,{contentType:p.mime,upsert:false});errDB(error);let {data}=supabase.storage.from('menu-images').getPublicUrl(path);return {url:data.publicUrl,thumbnail:data.publicUrl}}
function ids(v){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}
function numeric(v){let n=Number(v||0);if(!isFinite(n))throw Error('Número inválido');return n}
function enabled(v){return v===true||String(v).toLowerCase()==='true'}
async function checkout(p){let cfg=await settings();if(cfg.open!=='true')throw Error('Loja fechada');let name=String(p.customer||'').trim(),phone=String(p.phone||'').replace(/\D/g,'');if(name.length<2||phone.length<10)throw Error('Informe nome e telefone');if(!Array.isArray(p.items)||!p.items.length||p.items.length>60)throw Error('Carrinho inválido');if(p.delivery==='entrega'&&!String(p.address||'').trim())throw Error('Endereço obrigatório');
 let products=Object.fromEntries((await rows('products')).map(x=>[x.id,x])),addons=Object.fromEntries((await rows('addons')).map(x=>[x.id,x])),groups=Object.fromEntries((await rows('addon_groups')).map(x=>[x.id,x])),categories=Object.fromEntries((await rows('categories')).map(x=>[x.id,x]));let normalized=[],used={},subtotal=0;
 for(let line of p.items){let prod=products[line.id],qty=Number(line.qty);if(!prod||!enabled(prod.active)||!Number.isInteger(qty)||qty<1||qty>30)throw Error('Produto indisponível ou quantidade inválida');used[prod.id]=(used[prod.id]||0)+qty;let extra=0,options=[];
 for(let aid of [...new Set(line.addons||[])]){let a=addons[aid];if(!a||!enabled(a.active)||!ids(prod.addons).includes(aid))throw Error('Adicional indisponível');used[aid]=(used[aid]||0)+qty;let price=numeric(a.price);if(price<0)throw Error('Preço inválido');extra+=price;options.push({id:aid,name:a.name,price})}
 let allowed=[...new Set([...ids(prod.group_ids),...ids(categories[prod.category_id]?.group_ids)])],choice=line.choices||{};if(Object.keys(choice).some(id=>!allowed.includes(id)))throw Error('Grupo não pertence ao produto');
 for(let gid of allowed){let g=groups[gid];if(!g||!enabled(g.active))continue;let opts=JSON.parse(g.options||'[]'),selected=choice[gid]||[],counts={};if(!Array.isArray(selected))throw Error('Escolhas inválidas');for(let v of selected){let id=typeof v==='string'?v:v.id,units=typeof v==='string'?1:Number(v.qty);if(!id||!Number.isInteger(units)||units<1||units>30||counts[id])throw Error('Escolha duplicada/inválida');counts[id]=units}let amount=Object.values(counts).reduce((a,b)=>a+b,0),min=Math.max(numeric(g.min_select),enabled(g.required)?1:0),max=numeric(g.max_select)||opts.length;if(amount<min||amount>max)throw Error('Confira quantidades em '+g.name);
 for(let [id,units] of Object.entries(counts)){let opt=opts.find(x=>x.id===id);if(!opt||opt.active===false)throw Error('Opção indisponível');let linked=opt.product_id?products[opt.product_id]:null;if(opt.product_id&&(!linked||!enabled(linked.active)))throw Error('Produto vinculado indisponível');let val=opt.price!==''&&opt.price!==null&&opt.price!==undefined?numeric(opt.price):linked?numeric(linked.sale_price||linked.price):0;if(val<0)throw Error('Preço inválido');if(linked)used[linked.id]=(used[linked.id]||0)+qty*units;extra+=val*units;options.push({id,group:g.name,name:opt.name||linked?.name||'',price:val,qty:units})}}
 let price=numeric(prod.sale_price||prod.price);if(price<0)throw Error('Preço inválido');subtotal+=qty*(price+extra);normalized.push({id:prod.id,name:prod.name,qty,price,addons:options})}
 for(let [id,count] of Object.entries(used)){let v=products[id]||addons[id];if(enabled(v.stock_enabled)&&numeric(v.stock)<count)throw Error('Estoque insuficiente: '+v.name)}
 let fee=p.delivery==='entrega'?numeric(cfg.delivery_fee):0;if(p.delivery==='entrega'&&subtotal>=numeric(cfg.free_shipping||999999))fee=0;let discount=0,code=String(p.coupon||'').trim().toUpperCase();
 if(code){let cup=(await rows('coupons')).find(c=>String(c.code).toUpperCase()===code&&enabled(c.active));if(!cup)throw Error('Cupom inválido');let now=new Date().toISOString();if(cup.starts_at&&now<String(cup.starts_at).replace(' ','T'))throw Error('Cupom ainda não começou');if(cup.ends_at&&now>String(cup.ends_at).replace(' ','T'))throw Error('Cupom expirado');let previous=(await rows('orders')).filter(x=>String(x.coupon||'').toUpperCase()===code&&x.status!=='cancelado');if(numeric(cup.usage_limit)>0&&previous.length>=numeric(cup.usage_limit))throw Error('Cupom esgotado');if(numeric(cup.per_phone_limit)>0&&previous.filter(x=>String(x.phone)===phone).length>=numeric(cup.per_phone_limit))throw Error('Limite de uso por cliente');let ip=ids(cup.include_products),ep=ids(cup.exclude_products),ic=ids(cup.include_categories),ec=ids(cup.exclude_categories),eligible=0;
 for(let item of normalized){let product=products[item.id],cat=product.category_id;if(ip.length&&!ip.includes(item.id)||ep.includes(item.id)||ic.length&&!ic.includes(cat)||ec.includes(cat)||enabled(cup.exclude_sale)&&numeric(product.sale_price)>0)continue;eligible+=item.qty*(item.price+item.addons.reduce((a,b)=>a+numeric(b.price)*(b.qty||1),0))}if(eligible<=0||subtotal<numeric(cup.min_total))throw Error('Cupom não aplicável');discount=Math.min(eligible,cup.type==='fixed'?numeric(cup.value):eligible*numeric(cup.value)/100);if(numeric(cup.max_discount)>0)discount=Math.min(discount,numeric(cup.max_discount))}
 let total=Math.round((subtotal+fee-discount)*100)/100;if(p.payment==='dinheiro'&&numeric(p.change_for)>0&&numeric(p.change_for)<total)throw Error('Troco menor que valor total');
 let orderInput={customer:name,phone,delivery:p.delivery,address:String(p.address||''),payment:p.payment||'pix',items:JSON.stringify(normalized),subtotal:Math.round(subtotal*100)/100,fee,discount,total,status:'recebido',created_at:new Date().toISOString(),change_for:p.payment==='dinheiro'?numeric(p.change_for):0,change_amount:p.payment==='dinheiro'?Math.max(0,numeric(p.change_for)-total):0,coupon:code};
 const order=await commitCheckout(orderInput,used);
 return {id:order.id,total,status:'recebido',pix_key:p.payment==='pix'?cfg.pix_key:null,pix_copy_paste:p.payment==='pix'&&cfg.pix_key?pixCode(cfg.pix_key,total,cfg.store_name):null};}
async function statusUpdate(p){let valid=['recebido','preparando','pronto','em entrega','concluido','cancelado'];if(!valid.includes(p.status))throw Error('Status inválido');let o=(await rows('orders')).find(x=>String(x.id)===String(p.id));if(!o)throw Error('Pedido não encontrado');if(o.status==='concluido'&&p.status!=='concluido')throw Error('Pedido concluído');if(o.status==='cancelado'&&p.status!=='cancelado')throw Error('Pedido cancelado');await save('orders',p.id,{status:p.status},'PATCH');if(p.status==='concluido'&&o.status!=='concluido'){let pts=Math.max(0,Math.floor(numeric(o.subtotal)-numeric(o.discount)));let previous=(await rows('loyalty')).find(x=>String(x.phone)===String(o.phone));if(previous)await save('loyalty',previous.id,{points:numeric(previous.points)+pts},'PATCH');else await save('loyalty','',{phone:o.phone,points:pts},'POST')}return {ok:true}}
function pixCode(key,amount,name){function field(id,v){return id+String(v.length).padStart(2,'0')+v}function norm(s,max){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9 .-]/g,'').slice(0,max)}let data=field('00','br.gov.bcb.pix')+field('01',key),payload=field('00','01')+field('26',data)+field('52','0000')+field('53','986')+field('54',numeric(amount).toFixed(2))+field('58','BR')+field('59',norm(name||'LOJA',25))+field('60','BRASIL')+field('62',field('05','***'))+'6304',crc=0xffff;for(let i=0;i<payload.length;i++){crc^=payload.charCodeAt(i)<<8;for(let b=0;b<8;b++)crc=crc&0x8000?(crc<<1^0x1021)&65535:crc<<1&65535}return payload+crc.toString(16).toUpperCase().padStart(4,'0')}


async function dispatch(action,p,secret){if(action==='ping')return {status:'ok',provider:'Supabase',time:new Date().toISOString()};if(action==='catalog')return publicData();if(action==='checkout')return checkout(p);await authorized(secret);
if(action==='bootstrap'){let out={};for(let k of ['categories','products','addons','addon_groups','banners','coupons','orders','rewards'])out[k]=await rows(k);return {...out,settings:await settings()}}
if(action==='orders_live')return rows('orders');
if(action==='settings')return updateSettings(p);
if(action==='manage'){assert(['products','categories','addons','addon_groups','banners','coupons','rewards'].includes(p.table),'Tabela inválida');assert(['POST','PATCH','DELETE'].includes(p.method),'Método inválido');if(['products','addons'].includes(p.table)&&Number(p.data?.price||0)<0)throw Error('Preço inválido');return save(p.table,p.id,p.data,p.method)}
if(action==='reorder'){assert(Array.isArray(p.changes)&&p.changes.length<=100,'Reordenação inválida');for(let ch of p.changes){assert(['categories','products'].includes(ch.table),'Tabela inválida');await save(ch.table,ch.id,ch.data,'PATCH')}return {ok:true}}
if(action==='order_status')return statusUpdate(p);
if(action==='upload')return upload(p);
throw Error('Ação não permitida')}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{headers:cors,status:204});if(req.method!=='POST')return new Response(JSON.stringify({ok:false,error:'Método inválido'}),{status:405,headers:cors});try{const body=await req.json();assert(body&&typeof body.action==='string'&&body.data!==null&&typeof body.data==='object'&&!Array.isArray(body.data),'Requisição inválida');const result=await dispatch(body.action,body.data,(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,''));return new Response(JSON.stringify({ok:true,data:result}),{status:200,headers:cors})}catch(e){const msg=String(e?.message||e);return new Response(JSON.stringify({ok:false,error:msg}),{status:/login|permissão|Sessão/.test(msg)?401:400,headers:cors})}});
